# Generated by Django 5.2.1 on 2025-05-23 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klien',
            fields=[
                ('no_identitas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_registrasi', models.DateField()),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'db_table': 'klien',
            },
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('no_identitas_klien', models.OneToOneField(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataklien.klien')),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'individu',
            },
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('no_identitas_klien', models.OneToOneField(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataklien.klien')),
                ('nama_perusahaan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perusahaan',
            },
        ),
    ]
