# Generated by Django 5.2.1 on 2025-05-23 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('dosis', models.TextField()),
            ],
            options={
                'db_table': 'obat',
            },
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('kode_perawatan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_perawatan', models.CharField(max_length=100)),
                ('biaya_perawatan', models.IntegerField()),
            ],
            options={
                'db_table': 'perawatan',
            },
        ),
        migrations.CreateModel(
            name='PerawatanObat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kuantitas_obat', models.IntegerField()),
                ('kode_obat', models.ForeignKey(db_column='kode_obat', on_delete=django.db.models.deletion.CASCADE, to='perawatan_hewan.obat')),
                ('kode_perawatan', models.ForeignKey(db_column='kode_perawatan', on_delete=django.db.models.deletion.CASCADE, to='perawatan_hewan.perawatan')),
            ],
            options={
                'db_table': 'perawatan_obat',
                'unique_together': {('kode_perawatan', 'kode_obat')},
            },
        ),
        migrations.AddField(
            model_name='perawatan',
            name='obat_terkait',
            field=models.ManyToManyField(related_name='perawatan_menggunakan', through='perawatan_hewan.PerawatanObat', to='perawatan_hewan.obat'),
        ),
    ]
