# Generated by Django 5.2.1 on 2025-05-23 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('no_pegawai', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_mulai_kerja', models.DateField()),
                ('tanggal_akhir_kerja', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='FrontDesk',
            fields=[
                ('no_front_desk', models.OneToOneField(db_column='no_front_desk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.pegawai')),
            ],
            options={
                'db_table': 'front_desk',
            },
        ),
        migrations.CreateModel(
            name='TenagaMedis',
            fields=[
                ('no_tenaga_medis', models.OneToOneField(db_column='no_tenaga_medis', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.pegawai')),
                ('no_izin_praktik', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tenaga_medis',
            },
        ),
        migrations.AddField(
            model_name='pegawai',
            name='email_user',
            field=models.OneToOneField(db_column='email_user', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.CreateModel(
            name='DokterHewan',
            fields=[
                ('no_dokter_hewan', models.OneToOneField(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.tenagamedis')),
            ],
            options={
                'db_table': 'dokter_hewan',
            },
        ),
        migrations.CreateModel(
            name='PerawatHewan',
            fields=[
                ('no_perawat_hewan', models.OneToOneField(db_column='no_perawat_hewan', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.tenagamedis')),
            ],
            options={
                'db_table': 'perawat_hewan',
            },
        ),
        migrations.CreateModel(
            name='SertifikatKompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_sertifikat_kompetensi', models.CharField(max_length=10)),
                ('nama_sertifikat', models.CharField(max_length=100)),
                ('no_tenaga_medis', models.ForeignKey(db_column='no_tenaga_medis', on_delete=django.db.models.deletion.CASCADE, to='authentication.tenagamedis')),
            ],
            options={
                'db_table': 'sertifikat_kompetensi',
                'unique_together': {('no_sertifikat_kompetensi', 'no_tenaga_medis')},
            },
        ),
        migrations.CreateModel(
            name='JadwalPraktik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('jam', models.CharField(max_length=20)),
                ('no_dokter_hewan', models.ForeignKey(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.CASCADE, to='authentication.dokterhewan')),
            ],
            options={
                'db_table': 'jadwak_praktik',
                'unique_together': {('no_dokter_hewan', 'hari', 'jam')},
            },
        ),
    ]
