# Generated by Django 5.2.1 on 2025-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vaksin',
            table='vaksin',
        ),
    ]
