# Generated by Django 5.2.1 on 2025-05-23 09:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('hewan_peliharaan', '0001_initial'),
        ('manajemen_vaksin', '0002_alter_vaksin_table'),
        ('perawatan_hewan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.UUIDField(db_column='id_kunjungan', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe_kunjungan', models.CharField(choices=[('REGULER', 'Reguler'), ('VAKSINASI', 'Vaksinasi'), ('DARURAT', 'Darurat'), ('KONTROL', 'Kontrol')], max_length=10)),
                ('timestamp_awal', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_akhir', models.DateTimeField(blank=True, null=True)),
                ('suhu', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hewan_peliharaan.hewan')),
                ('kode_vaksin', models.ForeignKey(blank=True, db_column='kode_vaksin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_vaksin.vaksin')),
                ('no_dokter_hewan', models.ForeignKey(db_column='no_dokter_hewan', on_delete=django.db.models.deletion.PROTECT, to='authentication.dokterhewan')),
                ('no_front_desk', models.ForeignKey(db_column='no_front_desk', on_delete=django.db.models.deletion.PROTECT, to='authentication.frontdesk')),
                ('no_perawat_hewan', models.ForeignKey(db_column='no_perawat_hewan', on_delete=django.db.models.deletion.PROTECT, to='authentication.perawathewan')),
            ],
            options={
                'db_table': 'kunjungan',
            },
        ),
        migrations.CreateModel(
            name='KunjunganKeperawatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('kode_perawatan', models.ForeignKey(db_column='kode_perawatan', on_delete=django.db.models.deletion.PROTECT, to='perawatan_hewan.perawatan')),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunjungan.kunjungan')),
            ],
            options={
                'db_table': 'kunjungan_keperawatan',
                'unique_together': {('kunjungan', 'kode_perawatan')},
            },
        ),
    ]
