# Generated by Django 5.2.1 on 2025-05-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hewan_peliharaan', '0001_initial'),
        ('kunjungan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunjungan',
            name='hewan',
            field=models.ForeignKey(db_column='nama_hewan', on_delete=django.db.models.deletion.PROTECT, to='hewan_peliharaan.hewan'),
        ),
    ]
