# Generated by Django 5.2.1 on 2025-05-23 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataklien', '0001_initial'),
        ('jenis_hewan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id_hewan', models.UUIDField(db_column='id_hewan_internal', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('url_foto', models.CharField(max_length=255)),
                ('id_jenis', models.ForeignKey(db_column='id_jenis', on_delete=django.db.models.deletion.PROTECT, to='jenis_hewan.jenishewan')),
                ('no_identitas_klien', models.ForeignKey(db_column='no_identitas_klien', on_delete=django.db.models.deletion.CASCADE, to='dataklien.klien')),
            ],
            options={
                'db_table': 'hewan',
                'unique_together': {('nama', 'no_identitas_klien')},
            },
        ),
    ]
